version: "3.1"
services:
  frontend-app:
    container_name: frontend-app
    image: node:12.9.1-alpine
    restart: always
    build:
      context: ./frontend-app
      dockerfile: Dockerfile
    volumes:
      - ./frontend-app:/usr/src/frontend-app
      - /usr/src/frontend-app/node_modules
    working_dir: /usr/src/frontend-app
    command: yarn start
    ports:
      - 3000:3000
    depends_on:
      - backend-app
    networks:
      - backend-app
  backend-app:
    container_name: backend-app
    image: node:12.9.1-alpine
    restart: always
    build:
      context: ./backend-app
      dockerfile: Dockerfile
    volumes:
      - ./backend-app:/usr/src/backend-app
      - /usr/src/backend-app/node_modules
    working_dir: /usr/src/backend-app
    command: yarn start
    ports:
      - 5000:5000
      - 35729:35729
    networks:
      - backend-app
networks:
  backend-app:
    driver: bridge
