version: "3.1"
services:
  frontend-app:
    container_name: frontend-app
    image: node:12.9.1-alpine
    restart: always
    build: ./frontend-app/
    volumes:
      - ./frontend-app:/application-frontend
    working_dir: /application-frontend
    ports:
      - 3000:3000
    depends_on:
      - backend-app
    networks:
      - backend-app
  backend-app:
    container_name: backend-app
    image: node:12.9.1-alpine
    restart: always
    build: ./backend-app/
    volumes:
      - ./backend-app:/application-backend
    working_dir: /application-backend
    ports:
      - 5000:5000
      - 35729:35729
    networks:
      - backend-app
networks:
  backend-app:
    driver: bridge
